sudo: required
services:
  - docker

before_install:
  - docker build -t hamicch/docker-react -f Dockerfile.dev .

script:
  - docker run hamicch/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-250256537807"
  bucket_path: "docker-react"
  on:
    repo: hamicch/docker-react
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
